GET http://localhost:8080/api/admin/users

###
GET localhost:8080/api/admin/users/1001

###
GET  localhost:8080/api/admin/users/100

###
GET http://localhost:8080/api/admin/users
#token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidWtvNyIsInVpZCI6IjIyMiIsImlhdCI6MTczMTMyNDU1NSwiZXhwIjoxNzMxNDEwOTU1fQ.Lc1d3818hWMx-vekHfGbauv9lG57huVsPmPNtVaGJUI
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicXdodiIsInVpZCI6IjEiLCJpYXQiOjE3MzEzMjQ1MTYsImV4cCI6MTczMTQxMDkxNn0.XvhVFvzmnSklApyUmGSbwykUThv346OIhkUfv2iH8Kk
