spring:
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

    #1.先将模块结构整理好
    #2.写配置文件，日志+Jackson
    #3.创建新类型,在exception异常下，枚举类型，设置通用业务码。
###########################
my:
  secretkey: R28K42ZEJ8LWRHU5
#    1.添加安全类依赖
#    2.exception包下，至少一个自定义unchecked异常，包括处理通用业务异常，以及自定义异常
#    3.controller包下，创建ExceptionController组件，统一处理异常
#    4.component包下，创建PasswordEncoderConfig配置类
#    5.component包创建WTComponent组卷，注入配置中密钥，实现token的加密/解密
#    6.扩展User类，追加role属性，以及USER/ADMIN常量，为密码属性添加序列化忽略注解
#    7.扩展UserService组件中集合对象数据，密码123456的一个编码
